# Configuration file for ebook organization script
# Extract metadata from the file
use_file_meta: true

# if all metadata is provided within the file use them and end
use_file_meta_only: false

# Use LLM to enhance metadata extraction
use_llm: true

# Find metadata through Google Books API
google_api: true

# Use Open Library API for metadata
open_library_api: true

# Logging configuration
logging: true
logging_level: 'INFO'  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
logging_file: 'logs/ebook_organizer.log'

# Write metadata to output files
write_metadata: true

# Input and output folders for ebooks
input_folder: 'F:\Prace\Organizers\Ebooks\unorganized_ebooks'
output_folder: 'L:\Knihovna\Knihy'

# Enrich metadata true/false:
ALL_METADATA_KEYS:
  author: true
  title: true
  year: true
  isbn: true
  publisher: true
  language: true
  description: true
  series: true
  series_index: true
  subjects: true
  cover: true
  page_count: true
  identifiers: true
  contributors: false
  rights: false
  format: false
  source: false
